### PR TITLE
Semisupervised

### PR DESCRIPTION
**Pull request by vassilinast**
This branch contains new functionalities: retraining the autoencoder model using a semisupervised technique and training a classifier using the clustering, in order to use it in online mode.
Newly added files:
constraints.py: this script is used for setting pairwise constraints between random vocalizations of a recording for clustering evaluation purposes
clustering_ev.py: this script is used for evaluating a clustering by calculating how many of the annotated pairs (by constraints.py) are grouped together or not according to the clustering
Changed files: 
main_live.py: 
1) remove the offline debugging part
2) changed the way the syllables are written to the .csv file. The last USV of each 750 ms frame might be cut. Up to now, if that was the case, we had to read the whole .csv file and rewrite it, changing the last syllable entry. Now, we don't write the last syllable until we are sure it is not cut. In this way, we don't need to read the whole file every time, which can be not efficient for long recordings.
3) added the classifier functionality; the user can define a classifier to be used for classifying every detected USV

training_task.py:
added a function for model retraining, if the user chooses the specific functionality from the GUI

main.py:
GUI changes and minor cleaning up of the code

requirements.txt: the code runs fine with these modules versions. It can be checked by running main.py and main_live.py (extensive guidelines in README, which has also been modified about the semisupervised functionalities)

syllables_comp.py and audio_recognize.py have minor changes

### CODE REVIEW

**Comment by tyiannak** [comment]
@vassilinast please resolve the conflicts and add a few example tests in a comment here.

**Comment by vassilinast** [comment]
Example tests include main.py, main_live.py and training_task.py.

Try 
1) python3 main.py -i data/B148_test_small.wav -c y 
In the Dash GUI, you can check the clustering evaluation options (Global/Cluster/Point annotations). Moreover, you can choose the "Retrain model" button to check that it works (uses function from training_task.py). You can also click on the "Save clustering" button, which saves the clustering and trains a classifier based on it. For example, save the clustering, without retraining, with the agglomerative method and 6 clusters. 
2)  python3 main_live.py -i data/B148_test_small.wav
You can also try the classification functionality, (if you have saved the clustering configuration in 1) as python3 main_live.py -i data/B148_test_small.wav -c clf_B148_test_small_agg_6_deep.sav
3) python3 training_task.py -i data -ne 2
The second argument is the number of epochs. This script trains a convolutional autoencoder from scratch. Training data is from the "data" folder.

**Comment by tyiannak** [comment]
Getting this error:
`(venv) amvoc|semisupervised⚡ ⇒ python3 main.py -i data/B148_test_small.wav -c y
Computing spectrogram
100%|███████████████████████████████████████████████████████████████████████████████| 29998/29998 [00:00<00:00, 45049.48it/s]
(29999, 250)
Traceback (most recent call last):
  File "/Users/tyiannak/Research/libraries/amvoc/main.py", line 558, in <module>
    np.save('./dash/sp_time.npy', sp_time)
  File "<__array_function__ internals>", line 5, in save
  File "/Users/tyiannak/Research/libraries/amvoc/venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './dash/sp_time.npy'`

**Comment by vassilinast** [comment]
Fixed it. I was saving some data necessary for the dash app in a folder named dash, which I had manually created. I had forgotten to create it into the code if it didn't exist.

**Comment by tyiannak** [comment]
Ok it works now, but I am getting this issue when trying to run retrain model
https://github.com/matplotlib/matplotlib/issues/14304/

**Comment by tyiannak** [comment]
Everything seems to work as expected (tested on Mac OS and this time there was no issue with plotting during retraining). 
Some final minor tasks todo:
1) In Readme please make clear where are the outputs saved during running of main_live (in README we are saying that they are saved realtime_vocalizations.csv, while this seems that is not always the case - e.g. realtime_<filename> is the output name in case a wav file is provided). Also, when there's a model as input in main_live, there is a vocalisation cluster ID as an extra column in the csv. This must also be explained in the README file)
2) Readme needs some refactoring in terms of headers etc. Especially the unsupervised part needs to be explained as simple as possible
3) We need to remove some unused files such as untitled notebook, or kmeans_centers.npy

**Pull request merged**
